### ISSUE TITLE
Roadmap/To-do

### ISSUE THREAD

**Issue by tsukki9696** [tsukki9696/biscuit#3]
# Some things that need to be done
Think of this as a todo list or a roadmap of sorts

### Repository related
- [ ] Add the light theme palette and respective tiles and colors
- [ ] Link all ports in their respective README entries
- [ ] Add note in .Xresources mentioning the required patch for st users

### Port adjacent
- [ ] Rewrite nvim port
- [ ] Add light theme to existing themes

### Ports
- [ ] Wezterm
- [ ] Kitty
- [ ] XFCE Terminal
- [ ] GNOME Terminal
- [ ] Konsole

**Comment by tsukki9696** [comment]
Got some of the more minor stuff sorted out, will work on getting the nvim colorscheme remade properly

**Comment by ronindoll** [comment]
Someone has to make a gnome shell theme :3 I might if I have the time hmm (I'm just going to find & replace Marble shell theme's color codes with biscuits)(JK but not actually)

**Comment by tsukki9696** [comment]
Any help is appreciated, if you do end up doing it, submit a PR and put the respective files inside it's own directory

**Comment by afrolino02** [comment]
Hey everyone! I have a question, I have some contributions to do, some ports to YouTube music desktop client, HyDE themes for gallery, tauon client, zen-browser(I'm doing this right now) theme for steam millennium based on zehn interface...
Really thanks for this color scheme, that helps to keep my eyes fine... Must I fork this repo and send a pull request with each platform??
